### ISSUE TITLE
Tag a 4.1 version

### ISSUE THREAD

**Issue by ptxmac** [SFSafeSymbols/SFSafeSymbols#116]
#114 was merged a month ago, but no release have been tagged yet

**Comment by fredpi** [comment]
@ptxmac We'll release the tag once the discussion in https://github.com/SFSafeSymbols/SFSafeSymbols/pull/115 is finished :)

**Comment by fredpi** [comment]
@ptxmac [Version 4.1](https://github.com/SFSafeSymbols/SFSafeSymbols/releases/tag/4.1.0) is now released :)
