### ISSUE TITLE
Support Right-to-Left localization

### ISSUE THREAD

**Issue by n-studio** [SFSafeSymbols/SFSafeSymbols#118]
<img width="426" alt="Screenshot 2023-01-26 at 00 08 44" src="https://user-images.githubusercontent.com/617116/214614877-4f39fbe8-bc44-4a7d-9b4a-0cc9b46e6451.png">

For some symbols such as `arrow.up.backward.and.arrow.down.forward.circle`, SF Symbol suggests to use Right-to-Left localization to flip the symbol horizontally.

But `.arrowUpBackwardAndArrowDownForwardCircle.localized(to: .rtl)` will return `nil`.
Is Right-to-Left not supported?

**Comment by StevenSorial** [comment]
@n-studio We do support localizing to RTL, but it's only possible if that symbol supports explicit localization. Unfortunately, Apple did not add support for that symbol, it will only be implicit (when the whole app is using a RTL locale).

If you are using UIKit, you can force it using `imgView.semanticContentAttribute = .forceRightToLeft`

**Comment by n-studio** [comment]
It works great! Thank you!
