### ISSUE TITLE
Support for SF Symbols 5

### ISSUE THREAD

**Issue by FelixLisczyk** [SFSafeSymbols/SFSafeSymbols#124]
Are there any plans to support SF Symbols 5? This new version was officially released a few weeks ago.

https://developer.apple.com/sf-symbols/

Thank you very much for this great library! I use it in all of my apps. ❤️

**Comment by AF-cgi** [comment]
Any updates?

**Comment by StevenSorial** [comment]
I've created a [v5 branch](https://github.com/SFSafeSymbols/SFSafeSymbols/tree/work/v5) a few days ago that you can use in Cocoapods or SPM. i will try to merge it soon and create a release

**Comment by StevenSorial** [comment]
SFSafeSymbols 5.2.0 is now released
