### ISSUE TITLE
Support for visionOS 1.0

### ISSUE THREAD

**Issue by sebj** [SFSafeSymbols/SFSafeSymbols#127]
It'd be very helpful if symbols, and the custom initializer extensions, could be marked as available on visionOS 1.0.

Thanks!

**Comment by StevenSorial** [comment]
SFSafeSymbols 5.2.0 is released with visionOS support. 
please let me know if I missed any initializers.

**Comment by sebj** [comment]
Thanks very much, all looks good to me!
