### ISSUE TITLE
Release 5.2.1

### ISSUE THREAD

**Issue by Joannis** [SFSafeSymbols/SFSafeSymbols#131]
Would you be willing to cut a new release containing #128 ?

**Comment by StevenSorial** [comment]
@Joannis Will try to do that in the coming days

**Comment by samsonjs** [comment]
edit: I'm going to delete my fork soon, so don't use this anymore!
~Anyone who's itching to try Swift 6 can use 5.2.1 from my fork and then switch back once it's been released in this repo: https://github.com/samsonjs/SFSafeSymbols~

(I have no intent to maintain a fork so you will absolutely want to switch back)

**Comment by StevenSorial** [comment]
Version 5.3 is released
