### ISSUE TITLE
Use the original source for extracting icons names

### ISSUE THREAD

**Issue by auramagi** [SFSafeSymbols/SFSafeSymbols#33]
Hi!
I tracked down a way to get the original metadata for icon names. All San Francisco font files that include SF Symbols contain an encrypted font table inside. I released [a tool](https://github.com/auramagi/SFSymbolsMetadata) that can extract that data.

**Comment by fredpi** [comment]
@auramagi That's great! I will try to use your repo as the data source for SFSafeSymbols ;)

**Comment by fredpi** [comment]
Closing this as we still need the SFSymbols app to get the actual icons (see #37)
