### ISSUE TITLE
Show actual symbol in docs

### ISSUE THREAD

**Issue by yonaskolb** [SFSafeSymbols/SFSafeSymbols#37]
As Xcode in Catalina can actually show SF Symbols when used in strings it would be awesome to generate docs for each symbol so Xcode can show it in auto completion

<img width="629" alt="Screen Shot 2019-12-03 at 1 17 02 pm" src="https://user-images.githubusercontent.com/2393781/70014557-3d5add00-15cf-11ea-94e3-67d8163e7cc7.png">
<img width="512" alt="Screen Shot 2019-12-03 at 1 14 46 pm" src="https://user-images.githubusercontent.com/2393781/70014558-3d5add00-15cf-11ea-9083-ebfe1b038565.png">

**Comment by fredpi** [comment]
Thanks for the suggestion! Do you have any idea how we could automate the process of generating these docs?

**Comment by yonaskolb** [comment]
I don’t know of a way of creating them with code. Best I can think of is sorting the symbols by name in the SFSymbol app, copy and pasting them, and then getting the names (however you’re doing that) in the same sort order. Then you can match them up

**Comment by fredpi** [comment]
@yonaskolb I've released a new version with these changes: https://github.com/piknotech/SFSafeSymbols/releases/tag/1.1.0

**Comment by yonaskolb** [comment]
Awesome, thank you @fredpi! Nice work!
