### ISSUE TITLE
Some images are not supported

### ISSUE THREAD

**Issue by tungfam** [SFSafeSymbols/SFSafeSymbols#53]
Hello dear creators,

Found out that at least these images are not available:
- paintpalette.fill
- seal.fill

Do you plan to support it? Or am I doing something wrong while using them?

**Comment by fredpi** [comment]
@tungfam Thanks for raising this issue! 👍

You're right, somehow the parser didn't find these symbols.
However, with the release of the next version SFSafeSymbols (happening within the next 2 weeks), that will be fixed.

Until then, I'll leave this issue open.

**Comment by fredpi** [comment]
@tungfam A short update: Due to the missing release of macOS Big Sur, the update will only happen as soon as Big Sur is released. That might take some more weeks than the 2 weeks I suggested in my previous reply.

**Comment by tungfam** [comment]
Many thanks for the update! 
Sounds great 👍

**Comment by fredpi** [comment]
@tungfam The [2.0.0 release](https://github.com/piknotech/SFSafeSymbols/releases/tag/2.0.0) is now available and fixes this issue.
