### ISSUE TITLE
SPM issue

### ISSUE THREAD

**Issue by yonaskolb** [SFSafeSymbols/SFSafeSymbols#68]
Running `swift build` on this package leads to:
```
Source files for target SFSafeSymbolsTests should be located under 'Tests/SFSafeSymbolsTests', or a custom sources path can be set with the 'path' property in Package.swift
```

This also means the project can't be regenerated with `swift package generate-xcodeproj`

**Comment by fredpi** [comment]
Thanks! https://github.com/piknotech/SFSafeSymbols/pull/57 fixed a similar issues for the source files, but I forgot to also apply the fix to the test files.
