### ISSUE TITLE
M1, Simulator: Could not find module 'SFSafeSymbols' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by mvarie** [SFSafeSymbols/SFSafeSymbols#73]
Using Xcode 12.5, on a M1 Mac, when trying to run an iOS app that references SFSafeSymbols via Swift Package Manager, on one of the iOS simulators, the following compiler error appears:

`Could not find module 'SFSafeSymbols' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator`

When running on a physical iPhone, there are no issues. This only happens when trying to run the app in an iOS simulator.

**Comment by StevenSorial** [comment]
@mvarie try setting `Build Active Architure Only` build setting to YES

**Comment by mvarie** [comment]
@StevenMagdy thank you for your response. I've tried that, but the error still appears.

**Comment by mvarie** [comment]
@StevenMagdy my bad - the project was coming from an Intel machine and it had `arm64` as an _excluded_ architecture for Any iOS Simulator SDK. The issue was completely unrelated to your repository. My apologies.
