### ISSUE TITLE
Symbol preview

### ISSUE THREAD

**Issue by jbouaziz** [SFSafeSymbols/SFSafeSymbols#76]
Hi!

I was going over the code and generated enum values and I believe that this project is fixing the biggest issue with SFSymbols which is: replacing strings with safe enum values.

One suggestion is to add the symbol preview in the enum comment? It's possible to get all the symbols using the "Right Click > Copy Symbols" in the SF Symbols app. Same way that you're using the Copy Names feature to get the .txt file I believe?

I've made a json file with the symbol name and it's corresponding preview, it's available here https://gist.github.com/jbouaziz/11727f81c84134764ba0c491929b97f0

What do you think?

**Comment by StevenSorial** [comment]
@jbouaziz [its already implemented](https://github.com/piknotech/SFSafeSymbols/blob/stable/Sources/SFSafeSymbols/Enum/SFSymbol.swift#L5). Is there something I'm missing?

**Comment by jbouaziz** [comment]
Whoops sorry I was looking at the code on git and it doesn't show symbols. My bad.
