### ISSUE TITLE
Xcode 13.0 compile issue

### ISSUE THREAD

**Issue by victormihaita** [SFSafeSymbols/SFSafeSymbols#77]
The package is not compiling on XCode13. When can we get an update?

**Comment by fredpi** [comment]
@victormihaita Sorry for the long delay. I'm committed to push an update within the next 10 days.

**Comment by rygood** [comment]
@victormihaita can you try now? I've not seen this issue with Xcode 13.1 (13A1030d).

**Comment by fredpi** [comment]
This should now be fixed with the [3.3 release](https://github.com/SFSafeSymbols/SFSafeSymbols/releases/tag/3.3).
