### ISSUE TITLE
as-is-symbols.txt file missing iOS 15.2 information and has one malformed line

### ISSUE THREAD

**Issue by Larry-Gensch** [SFSafeSymbols/SFSafeSymbols#92]
There seems to be one malformed line in the `as-is-symbols.txt` file (the upper case character is incorrect)

> "livephotoPlay" = "This symbol may not be modified and may only be used to refer to Apple’s Live Photos feature.";

This should be:

> "livephoto.play" = "This symbol may not be modified and may only be used to refer to Apple’s Live Photos feature.";

In addition, I noticed a few missing entries for the latest iOS version:

> "airpod.gen3.left" = "This symbol may not be modified and may only be used to refer to Apple’s AirPods.";
> "airpod.gen3.right" = "This symbol may not be modified and may only be used to refer to Apple’s AirPods.";
> "airpods.gen3" = "This symbol may not be modified and may only be used to refer to Apple’s AirPods.";
> "airpods.gen3.chargingcase.wireless" = "This symbol may not be modified and may only be used to refer to Apple’s AirPods.";
> "airpods.gen3.chargingcase.wireless.fill" = "This symbol may not be modified and may only be used to refer to Apple’s AirPods.";
> "appclip" = "This symbol may not be modified and may only be used to refer to Apple’s App Clips.";
> "beats.fit.pro" = "This symbol may not be modified and may only be used to refer to Beats headphones.";
> "beats.fit.pro.chargingcase" = "This symbol may not be modified and may only be used to refer to Beats headphones.";
> "beats.fit.pro.chargingcase.fill" = "This symbol may not be modified and may only be used to refer to Beats headphones.";
> "beats.fit.pro.left" = "This symbol may not be modified and may only be used to refer to Beats headphones.";
> "beats.fit.pro.right" = "This symbol may not be modified and may only be used to refer to Beats headphones.";

(These may be iOS 15.2 related, which this project may not be up to date with.)

Since I was only interested in the "restricted" or "as-is" nature of the symbols, I haven't checked whether or not there are other iOS 15.2 issues.

My interest here is that somebody is tracking the restricted/as-is symbols, and this is the most up-to-date project that seems to do so. I would like to track this file in the future, and perhaps assist in helping keep it up to date to ensure it remains definitive for current and future versions of SF Symbols.

Also note: The current AppleScript does not work with the latest SF Symbols app from Apple, version 3.2 (67). The current SF Symbols app makes is very difficult to get these symbols, and your AppleScript, which seems to be version dependent, is a great start. I managed to pick up ALL the symbols manually (looking for the (i) symbol and copying names/reasons). Your AppleScript, if it worked, would make that job a bit easier. Keep up the good work!

I've attached a modified as-is-symbols.txt to help you make any necessary fixes.

[as-is-symbols.txt](https://github.com/SFSafeSymbols/SFSafeSymbols/files/7796704/as-is-symbols.txt)

**Comment by fredpi** [comment]
@Larry-Gensch Thank you for raising this issue!

We are a currently behind with our releases (and adjustments to SF Symbols 3.2) due to ongoing discussions in https://github.com/SFSafeSymbols/SFSafeSymbols/pull/90 which first need clarification, but in the future it will be (hopefully) quite easy to keep this repo up-to-date. So it will be possible for you to track our as-is-symbols file and assume it is current. You can also help keeping it up-to-date (see the [contributing guide](https://github.com/SFSafeSymbols/SFSafeSymbols/blob/stable/CONTRIBUTING.md)).

The missing as-is-symbols are indeed SF Symbols 3.2 (iOS 15.2) related; those issues will be resolved once we update to it (after https://github.com/SFSafeSymbols/SFSafeSymbols/pull/90 is merged).

The `livephotoPlay` text which you detected seems like a weird artifact... Also it's unfortunate that the script doesn't work any longer... @StevenMagdy Could you comment on these observations (because you wrote the as-is-symbols script in the first place)?

**Comment by StevenSorial** [comment]
@Larry-Gensch Thank you for raising this issue!

As @fredpi Mentioned, the missing symbols are related to the 3.2 symbols which are not implemented yet. That is also why I didn't run the script on the latest app version.

The good news is that I found out how to get the list from Apple similar to how we get the symbols list. Apple Includes this information in an internal framework called `CoreGlyphs`.

You can get this list from multiple sources based on which version of SFSymbols you want:

* macOS: `./System/Library/CoreServices/CoreGlyphs.bundle/Contents/Resources/symbol_restrictions.strings`
* Xcode Built-in Simulator: `./Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/CoreGlyphs.bundle/symbol_restrictions.strings`
* Xcode downloaded Simulator (13.0): `./Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 13.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreServices/CoreGlyphs.bundle/symbol_restrictions.strings`

You can then convert the strings file to plist using `plutil`.

Thanks to @auramagi for the info found in [SFSymbolsMetadata](https://github.com/auramagi/SFSymbolsMetadata/issues/4#issuecomment-660779621)

**Comment by knothed** [comment]
Closed via https://github.com/SFSafeSymbols/SFSafeSymbols/pull/96. Release coming soon :)
