### ISSUE TITLE
Unit tests for correct symbols

### ISSUE THREAD

**Issue by MartinW** [SFSafeSymbols/SFSafeSymbols#93]
Add unit tests to check that the correct symbol is being retrieved using XCTAssert. Compare Image(systemName:) value against Image(systemSymbol:) value. Currently it only checks that it has not errored.

- Add sorting to test symbols in alphabetical order
- Add version tests
- Add success and fail tests for specific symbols

**Comment by fredpi** [comment]
Closed via #94
